### ISSUE TITLE
Config of the maximum number of function arguments

### ISSUE THREAD

**Issue by mcproger** [best-doctor/mr_proper#1]
How about limiting the number of arguments to a function? When a function seems to need more than two or three arguments, it is likely that some of those arguments ought to be wrapped into a function of their own. This will help to avoid situations with large function signatures and will certainly increase readability, as well as separation of logic.

**Comment by Melevir** [comment]
Lot of arguments really decreases readability, but doesn't make function non-pure. Since mr_proper is only about pure functions, this idea doesn't fits here.

But it's still a good idea for https://github.com/best-doctor/flake8-functions. I'll do it, thanks.

**Comment by Melevir** [comment]
Done.
